/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material_2} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material_3} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material_4} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material_5} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material_1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
